import type { NodeDimension } from "@/types.ts";

export const NODE_DIMENSIONS: Record<string, NodeDimension> = {
  inputText: { w: 220, h: 140, title: "INPUT TEXT", sub: "string data" },
  inputImage: { w: 220, h: 140, title: "INPUT IMAGE", sub: "base64 data" },
  customScript: { w: 260, h: 220, title: "CUSTOM SCRIPT", sub: "js execution" },
  httpRequest: { w: 240, h: 200, title: "HTTP REQUEST", sub: "fetch api" },
  jsonPath: { w: 220, h: 100, title: "JSON PATH", sub: "extract data" },
  outputText: { w: 280, h: 280, title: "OUTPUT TEXT", sub: "stream render" },
  outputImage: { w: 280, h: 260, title: "OUTPUT IMAGE", sub: "image render" },
  macroNode: { w: 260, h: 220, title: "MACRO NODE", sub: "sub-graph logic" },
  macroInEdge: { w: 180, h: 100, title: "MACRO IN (edge)", sub: "edge" },
  macroInParam: { w: 180, h: 100, title: "MACRO IN (param)", sub: "param" },
  macroOutput: { w: 180, h: 100, title: "MACRO OUT", sub: "pass through" },
  macroConnections: {
    w: 180,
    h: 100,
    title: "MACRO CONNS",
    sub: "active ports",
  },
  folderInput: { w: 220, h: 220, title: "FOLDER INPUT", sub: "load directory" },
  batchIterator: { w: 220, h: 160, title: "BATCH ITERATOR", sub: "loop items" },
  delay: { w: 220, h: 100, title: "DELAY", sub: "pause flow" },
  listAggregator: {
    w: 280,
    h: 220,
    title: "LIST AGGREGATOR",
    sub: "collect items",
  },
  downloadData: { w: 220, h: 160, title: "DOWNLOAD DATA", sub: "multi-format" },
  imageProcess: { w: 280, h: 420, title: "IMAGE PROCESS", sub: "resize/convert" },
  reviewNode: { w: 320, h: 400, title: "REVIEW", sub: "manual approval" },
  // Transformers.js nodes
  transformersPipeline: {
    w: 300,
    h: 300,
    title: "PIPELINE",
    sub: "transformers.js",
  },
  transformersModelLoader: {
    w: 300,
    h: 300,
    title: "MODEL LOADER",
    sub: "transformers.js",
  },
  transformersTokenizerLoader: {
    w: 280,
    h: 240,
    title: "TOKENIZER",
    sub: "transformers.js",
  },
  transformersProcessorLoader: {
    w: 280,
    h: 240,
    title: "PROCESSOR",
    sub: "transformers.js",
  },
  transformersGenerate: {
    w: 300,
    h: 340,
    title: "GENERATE",
    sub: "transformers.js",
  },
  transformersTokenizerEncode: {
    w: 260,
    h: 160,
    title: "ENCODE",
    sub: "tokenizer",
  },
  transformersTokenizerDecode: {
    w: 260,
    h: 140,
    title: "DECODE",
    sub: "tokenizer",
  },
  transformersProcessor: { w: 280, h: 200, title: "PROCESS", sub: "processor" },
  transformersChatTemplate: {
    w: 280,
    h: 200,
    title: "CHAT TEMPLATE",
    sub: "transformers.js",
  },
  transformersEnvConfig: {
    w: 260,
    h: 220,
    title: "ENV CONFIG",
    sub: "transformers.js",
  },
  transformersGenerationConfig: {
    w: 280,
    h: 340,
    title: "GEN CONFIG",
    sub: "parameters",
  },
  audioInput: { w: 220, h: 240, title: "AUDIO INPUT", sub: "audio data" },
  audioOutput: { w: 280, h: 180, title: "AUDIO OUTPUT", sub: "playback" },
  videoInput: { w: 220, h: 240, title: "VIDEO INPUT", sub: "video data" },
  transformersModelCall: {
    w: 260,
    h: 140,
    title: "MODEL CALL",
    sub: "forward pass",
  },
  transformersPostProcessCall: {
    w: 280,
    h: 200,
    title: "POST-PROCESS",
    sub: "call output",
  },
};
